Don't mix string with array (use $* instead of $@)

diff --git a/bash-config b/bash-config
--- a/bash-config
+++ b/bash-config
@@ -11,7 +11,7 @@ readonly SEPARATOR_INI=' = '
 
 
 error(){
-    echo "ERROR: $@" >&2
+    echo "ERROR: $*" >&2
 }
 
 get_line_number(){
