Refactor verify_write.

diff --git a/bash-config b/bash-config
--- a/bash-config
+++ b/bash-config
@@ -220,8 +220,9 @@ usage(){
 }
 
 verify_write(){
-    if [[ $(grep "^${parameter}${separator}${value}$" "$config" 2>/dev/null) != "${parameter}${separator}${value}" ]]; then
-        error "Failed to write '${parameter}${separator}${value}' to '$config'"
+    local fullstring=${parameter}${separator}${value}
+    if ! grep -q "^${fullstring}$" "$config" &>/dev/null; then
+        error "Failed to write '${fullstring}' to '$config'"
         exit 1
     fi
 }
